CREATE TABLE bot_users (
                           user_id BIGINT PRIMARY KEY,
                           display_name VARCHAR(255),
                           balance BIGINT DEFAULT 1000 NOT NULL,
                           last_gamble_time BIGINT DEFAULT 0 NOT NULL,
                           last_fifty_fifty_time BIGINT DEFAULT 0 NOT NULL,
                           last_farm_time BIGINT DEFAULT 0 NOT NULL,
                           last_multiply_time BIGINT DEFAULT 0,
                           last_fishing_time BIGINT DEFAULT 0 NOT NULL,
                           farm_upgrade BIGINT DEFAULT 0,
                           next_upgrade_price BIGINT DEFAULT 1000,
                           last_bossfight_time BIGINT DEFAULT 0,
                           last_poker_time BIGINT DEFAULT 0 NOT NULL,
                           gamble_upgrade INTEGER DEFAULT 0,
                           hp INTEGER DEFAULT 2500,
                           max_hp INTEGER DEFAULT 2500,
                           attack INTEGER DEFAULT 10,
                           defense INTEGER DEFAULT 5,
                           weapon VARCHAR(255) DEFAULT 'Кулаки',
                           armor VARCHAR(255) DEFAULT 'Рубаха',
                           boss_level INTEGER DEFAULT 0,
                           inventory VARCHAR(255) DEFAULT 'Кулаки,Рубаха',
                           consumables VARCHAR(255) DEFAULT ''
);
